import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
CMSIS/system_stm32f1xx.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_usart.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi.c
""")

src += ['CMSIS/startup_stm32f103xb.s']

# if rtconfig.CROSS_TOOL == 'gcc':
#     src += ['CMSIS/Device/ST/STM32F1xx/Source/Templates/gcc/startup_stm32f103xb.s']
# elif rtconfig.CROSS_TOOL == 'keil':
#     src += ['CMSIS/Device/ST/STM32F1xx/Source/Templates/arm/startup_stm32f103xb.s']
# elif rtconfig.CROSS_TOOL == 'iar':
#     src += ['CMSIS/Device/ST/STM32F1xx/Source/Templates/iar/startup_stm32f103xb.s']

# if GetDepend(['RT_USING_PIN']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c']
#     
# if GetDepend(['RT_USING_SERIAL']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c']
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_usart.c']
# 
# if GetDepend(['RT_USING_I2C']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2c.c']
#     
# if GetDepend(['RT_USING_SPI']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi.c']
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_spi.c']
# 
# if GetDepend(['RT_USING_USB_HOST']) or GetDepend(['RT_USING_USB_DEVICE']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.c']
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd_ex.c'] 
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c']
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_hcd.c']
# 
# if GetDepend(['RT_USING_CAN']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_can.c']
# 
# if GetDepend(['RT_USING_HWTIMER']) or GetDepend(['RT_USING_PWM']) or GetDepend(['RT_USING_PULSE_ENCODER']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c']
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c']
# 
# if GetDepend(['BSP_USING_ETH']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_eth.c']
# 
# if GetDepend(['RT_USING_ADC']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc.c']
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc_ex.c']
# 
# if GetDepend(['RT_USING_RTC']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc.c']
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc_ex.c']
# 
# if GetDepend(['RT_USING_WDT']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_iwdg.c']
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_wwdg.c']
# 
# if GetDepend(['RT_USING_SDIO']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_sdmmc.c']
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_sd.c']
# 
# if GetDepend(['RT_USING_AUDIO']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2s.c']
# 
# if GetDepend(['RT_USING_MTD_NOR']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_nor.c']
# 
# if GetDepend(['RT_USING_MTD_NAND']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_nand.c']
# 
# if GetDepend(['BSP_USING_EXT_SRAM']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_fsmc.c']
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_sram.c']
# 
# if GetDepend(['BSP_USING_ON_CHIP_FLASH']):
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c']
#     src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.c']

path = [cwd + '/CMSIS/Device/ST/STM32F1xx/Include', 
    cwd + '/STM32F1xx_HAL_Driver/Inc',
    cwd + '/STM32F1xx_HAL_Driver',
    cwd + '/CMSIS/Include',
    cwd + '/CMSIS']

CPPDEFINES = ['USE_HAL_DRIVER']
group = DefineGroup('STM32_HAL', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
