import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = Split('''
flash.c
gpio.c
read_uid.c
sdk.c
uart.c
usb_config.c
usbd_STM32F103.c
''')

path =  [cwd]

CPPDEFINES = ['STM32F103xB']
group = DefineGroup('daplink-ports', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
Return('group')
