# RT-Thread building script for bridge

import os
import rtconfig
Import ('RTT_ROOT')
from building import *

src = []
libs = []
objs = []
libpath = []
cpppath = []
cppdefines = []
cwd = GetCurrentDir()
list = os.listdir(cwd)

src += ['rtthread_port/cmsis_os2_port.c']
cpppath += [cwd + '/rtthread_port']

group = DefineGroup('daplink', src, depend = [''], CPPPATH = cpppath, CPPDEFINES = cppdefines, LIBS = libs, LIBPATH = libpath)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group
Return('objs')
